# Generated by Django 3.0.8 on 2020-07-24 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_photo_photoalbum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoalbum',
            name='user',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='PhotoAlbum',
        ),
    ]
